// Generated by scripts/capture-command-table.ts from redis 8.0.6, redis 7.4.4, redis 7.2.4, redis 7.0.15, redis 6.2.24, valkey 8.0.11, valkey 9.0.6. Do not edit by hand.
import type { CommandTableDelta, CommandTableEntry } from './command-table'

export const REDIS_80: Readonly<Record<string, CommandTableEntry>> = {
  acl: { flags: [], categories: ['@slow'] },
  'acl|dryrun': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  'acl|help': { flags: ['loading', 'stale'], categories: ['@slow'] },
  'acl|whoami': {
    flags: ['noscript', 'loading', 'stale'],
    categories: ['@slow'],
  },
  append: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  auth: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'no_auth', 'allow_busy'],
    categories: ['@fast', '@connection'],
  },
  bitcount: {
    flags: ['readonly'],
    categories: ['@read', '@bitmap', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  bitfield: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@bitmap', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update', 'variable_flags'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        notes: 'This command allows both access and modification of the key',
      },
    ],
  },
  bitfield_ro: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@bitmap', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  bitop: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@bitmap', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 3, lastKey: -1, keyStep: 1 },
    ],
  },
  bitpos: {
    flags: ['readonly'],
    categories: ['@read', '@bitmap', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  blmove: {
    flags: ['write', 'denyoom', 'blocking'],
    categories: ['@write', '@list', '@slow', '@blocking'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
      { flags: ['RW', 'insert'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  blmpop: {
    flags: ['write', 'blocking', 'movablekeys'],
    categories: ['@write', '@list', '@slow', '@blocking'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  blpop: {
    flags: ['write', 'blocking'],
    categories: ['@write', '@list', '@slow', '@blocking'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: -2,
        keyStep: 1,
      },
    ],
  },
  brpop: {
    flags: ['write', 'blocking'],
    categories: ['@write', '@list', '@slow', '@blocking'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: -2,
        keyStep: 1,
      },
    ],
  },
  bzmpop: {
    flags: ['write', 'blocking', 'movablekeys'],
    categories: ['@write', '@sortedset', '@slow', '@blocking'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  bzpopmax: {
    flags: ['write', 'blocking', 'fast'],
    categories: ['@write', '@sortedset', '@fast', '@blocking'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: -2,
        keyStep: 1,
      },
    ],
  },
  bzpopmin: {
    flags: ['write', 'blocking', 'fast'],
    categories: ['@write', '@sortedset', '@fast', '@blocking'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: -2,
        keyStep: 1,
      },
    ],
  },
  client: { flags: [], categories: ['@slow'] },
  'client|getname': {
    flags: ['noscript', 'loading', 'stale'],
    categories: ['@slow', '@connection'],
  },
  'client|help': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
  },
  'client|id': {
    flags: ['noscript', 'loading', 'stale'],
    categories: ['@slow', '@connection'],
  },
  'client|info': {
    flags: ['noscript', 'loading', 'stale'],
    categories: ['@slow', '@connection'],
    tips: ['nondeterministic_output'],
  },
  'client|kill': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous', '@connection'],
  },
  'client|list': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous', '@connection'],
    tips: ['nondeterministic_output'],
  },
  'client|no-evict': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous', '@connection'],
  },
  'client|setinfo': {
    flags: ['noscript', 'loading', 'stale'],
    categories: ['@slow', '@connection'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  'client|setname': {
    flags: ['noscript', 'loading', 'stale'],
    categories: ['@slow', '@connection'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  cluster: { flags: [], categories: ['@slow'] },
  'cluster|info': {
    flags: ['stale'],
    categories: ['@slow'],
    tips: ['nondeterministic_output'],
  },
  'cluster|myid': { flags: ['stale'], categories: ['@slow'] },
  'cluster|nodes': {
    flags: ['stale'],
    categories: ['@slow'],
    tips: ['nondeterministic_output'],
  },
  'cluster|shards': {
    flags: ['loading', 'stale'],
    categories: ['@slow'],
    tips: ['nondeterministic_output'],
  },
  'cluster|slots': {
    flags: ['loading', 'stale'],
    categories: ['@slow'],
    tips: ['nondeterministic_output'],
  },
  command: {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
    tips: ['nondeterministic_output_order'],
  },
  'command|count': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
  },
  'command|docs': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
    tips: ['nondeterministic_output_order'],
  },
  'command|getkeys': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
  },
  'command|getkeysandflags': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
  },
  'command|help': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
  },
  'command|info': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
    tips: ['nondeterministic_output_order'],
  },
  'command|list': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@connection'],
    tips: ['nondeterministic_output_order'],
  },
  config: { flags: [], categories: ['@slow'] },
  'config|get': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  'config|help': { flags: ['loading', 'stale'], categories: ['@slow'] },
  'config|resetstat': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  'config|rewrite': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  'config|set': {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  copy: {
    flags: ['write', 'denyoom'],
    categories: ['@keyspace', '@write', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['OW', 'update'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  dbsize: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    tips: ['request_policy:all_shards', 'response_policy:agg_sum'],
  },
  decr: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  decrby: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  del: {
    flags: ['write'],
    categories: ['@keyspace', '@write', '@slow'],
    tips: ['request_policy:multi_shard', 'response_policy:agg_sum'],
    keySpecs: [
      { flags: ['RM', 'delete'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  discard: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'allow_busy'],
    categories: ['@fast', '@transaction'],
  },
  echo: {
    flags: ['loading', 'stale', 'fast'],
    categories: ['@fast', '@connection'],
  },
  eval: {
    flags: [
      'noscript',
      'stale',
      'skip_monitor',
      'no_mandatory_keys',
      'movablekeys',
    ],
    categories: ['@slow', '@scripting'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        notes:
          'We cannot tell how the keys will be used so we assume the worst, RW and UPDATE',
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  eval_ro: {
    flags: [
      'readonly',
      'noscript',
      'stale',
      'skip_monitor',
      'no_mandatory_keys',
      'movablekeys',
    ],
    categories: ['@slow', '@scripting'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        notes:
          'We cannot tell how the keys will be used so we assume the worst, RO and ACCESS',
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  evalsha: {
    flags: [
      'noscript',
      'stale',
      'skip_monitor',
      'no_mandatory_keys',
      'movablekeys',
    ],
    categories: ['@slow', '@scripting'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  evalsha_ro: {
    flags: [
      'readonly',
      'noscript',
      'stale',
      'skip_monitor',
      'no_mandatory_keys',
      'movablekeys',
    ],
    categories: ['@slow', '@scripting'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  exec: {
    flags: ['noscript', 'loading', 'stale', 'skip_slowlog'],
    categories: ['@slow', '@transaction'],
  },
  exists: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    tips: ['request_policy:multi_shard', 'response_policy:agg_sum'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 }],
  },
  expire: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  expireat: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  expiretime: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  fcall: {
    flags: [
      'noscript',
      'stale',
      'skip_monitor',
      'no_mandatory_keys',
      'movablekeys',
    ],
    categories: ['@slow', '@scripting'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        notes:
          'We cannot tell how the keys will be used so we assume the worst, RW and UPDATE',
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  fcall_ro: {
    flags: [
      'readonly',
      'noscript',
      'stale',
      'skip_monitor',
      'no_mandatory_keys',
      'movablekeys',
    ],
    categories: ['@slow', '@scripting'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        notes:
          'We cannot tell how the keys will be used so we assume the worst, RO and ACCESS',
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  flushall: {
    flags: ['write'],
    categories: ['@keyspace', '@write', '@slow', '@dangerous'],
    tips: ['request_policy:all_shards', 'response_policy:all_succeeded'],
  },
  flushdb: {
    flags: ['write'],
    categories: ['@keyspace', '@write', '@slow', '@dangerous'],
    tips: ['request_policy:all_shards', 'response_policy:all_succeeded'],
  },
  function: { flags: [], categories: ['@slow'] },
  'function|delete': {
    flags: ['write', 'noscript'],
    categories: ['@write', '@slow', '@scripting'],
    tips: ['request_policy:all_shards', 'response_policy:all_succeeded'],
  },
  'function|dump': { flags: ['noscript'], categories: ['@slow', '@scripting'] },
  'function|flush': {
    flags: ['write', 'noscript'],
    categories: ['@write', '@slow', '@scripting'],
    tips: ['request_policy:all_shards', 'response_policy:all_succeeded'],
  },
  'function|help': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@scripting'],
  },
  'function|kill': {
    flags: ['noscript', 'allow_busy'],
    categories: ['@slow', '@scripting'],
    tips: ['request_policy:all_shards', 'response_policy:one_succeeded'],
  },
  'function|list': {
    flags: ['noscript'],
    categories: ['@slow', '@scripting'],
    tips: ['nondeterministic_output_order'],
  },
  'function|load': {
    flags: ['write', 'denyoom', 'noscript'],
    categories: ['@write', '@slow', '@scripting'],
    tips: ['request_policy:all_shards', 'response_policy:all_succeeded'],
  },
  'function|restore': {
    flags: ['write', 'denyoom', 'noscript'],
    categories: ['@write', '@slow', '@scripting'],
    tips: ['request_policy:all_shards', 'response_policy:all_succeeded'],
  },
  'function|stats': {
    flags: ['noscript', 'allow_busy'],
    categories: ['@slow', '@scripting'],
    tips: [
      'nondeterministic_output',
      'request_policy:all_shards',
      'response_policy:special',
    ],
  },
  geoadd: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  geodist: {
    flags: ['readonly'],
    categories: ['@read', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  geohash: {
    flags: ['readonly'],
    categories: ['@read', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  geopos: {
    flags: ['readonly'],
    categories: ['@read', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  georadius: {
    flags: ['write', 'denyoom', 'movablekeys'],
    categories: ['@write', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['OW', 'update'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STORE', startFrom: 6 },
      },
      {
        flags: ['OW', 'update'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STOREDIST', startFrom: 6 },
      },
    ],
  },
  georadius_ro: {
    flags: ['readonly'],
    categories: ['@read', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  georadiusbymember: {
    flags: ['write', 'denyoom', 'movablekeys'],
    categories: ['@write', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['OW', 'update'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STORE', startFrom: 5 },
      },
      {
        flags: ['OW', 'update'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STOREDIST', startFrom: 5 },
      },
    ],
  },
  georadiusbymember_ro: {
    flags: ['readonly'],
    categories: ['@read', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  geosearch: {
    flags: ['readonly'],
    categories: ['@read', '@geo', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  geosearchstore: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@geo', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  get: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@string', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  getbit: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@bitmap', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  getdel: {
    flags: ['write', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  getex: {
    flags: ['write', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        notes: 'RW and UPDATE because it changes the TTL',
      },
    ],
  },
  getrange: {
    flags: ['readonly'],
    categories: ['@read', '@string', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  getset: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  hdel: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hello: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'no_auth', 'allow_busy'],
    categories: ['@fast', '@connection'],
  },
  hexists: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  hexpire: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hexpireat: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hget: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hgetall: {
    flags: ['readonly'],
    categories: ['@read', '@hash', '@slow'],
    tips: ['nondeterministic_output_order'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hgetdel: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  hgetex: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        notes: 'RW and UPDATE because it changes the TTL',
      },
    ],
  },
  hincrby: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  hincrbyfloat: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  hkeys: {
    flags: ['readonly'],
    categories: ['@read', '@hash', '@slow'],
    tips: ['nondeterministic_output_order'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hlen: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  hmget: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hmset: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hpersist: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hpexpire: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hpexpireat: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hpttl: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hrandfield: {
    flags: ['readonly'],
    categories: ['@read', '@hash', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hscan: {
    flags: ['readonly'],
    categories: ['@read', '@hash', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hset: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hsetex: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hsetnx: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hstrlen: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  httl: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hvals: {
    flags: ['readonly'],
    categories: ['@read', '@hash', '@slow'],
    tips: ['nondeterministic_output_order'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  incr: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  incrby: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  incrbyfloat: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  info: {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@dangerous'],
    tips: [
      'nondeterministic_output',
      'request_policy:all_shards',
      'response_policy:special',
    ],
  },
  keys: {
    flags: ['readonly'],
    categories: ['@keyspace', '@read', '@slow', '@dangerous'],
    tips: ['request_policy:all_shards', 'nondeterministic_output_order'],
  },
  lastsave: {
    flags: ['loading', 'stale', 'fast'],
    categories: ['@admin', '@fast', '@dangerous'],
    tips: ['nondeterministic_output'],
  },
  lindex: {
    flags: ['readonly'],
    categories: ['@read', '@list', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  linsert: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@list', '@slow'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  llen: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@list', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  lmove: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@list', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
      { flags: ['RW', 'insert'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  lmpop: {
    flags: ['write', 'movablekeys'],
    categories: ['@write', '@list', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  lpop: {
    flags: ['write', 'fast'],
    categories: ['@write', '@list', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  lpos: {
    flags: ['readonly'],
    categories: ['@read', '@list', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  lpush: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@list', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  lpushx: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@list', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  lrange: {
    flags: ['readonly'],
    categories: ['@read', '@list', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  lrem: {
    flags: ['write'],
    categories: ['@write', '@list', '@slow'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  lset: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@list', '@slow'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  ltrim: {
    flags: ['write'],
    categories: ['@write', '@list', '@slow'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  mget: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@string', '@fast'],
    tips: ['request_policy:multi_shard'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  monitor: {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  move: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  mset: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@string', '@slow'],
    tips: ['request_policy:multi_shard', 'response_policy:all_succeeded'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: -1, keyStep: 2 },
    ],
  },
  msetnx: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@string', '@slow'],
    keySpecs: [
      { flags: ['OW', 'insert'], beginSearchIndex: 1, lastKey: -1, keyStep: 2 },
    ],
  },
  multi: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'allow_busy'],
    categories: ['@fast', '@transaction'],
  },
  persist: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  pexpire: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  pexpireat: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  pexpiretime: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  pfadd: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hyperloglog', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  pfcount: {
    flags: ['readonly'],
    categories: ['@read', '@hyperloglog', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access'],
        beginSearchIndex: 1,
        lastKey: -1,
        keyStep: 1,
        notes:
          'RW because it may change the internal representation of the key, and propagate to replicas',
      },
    ],
  },
  pfmerge: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@hyperloglog', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'insert'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: -1, keyStep: 1 },
    ],
  },
  ping: {
    flags: ['fast'],
    categories: ['@fast', '@connection'],
    tips: ['request_policy:all_shards', 'response_policy:all_succeeded'],
  },
  psetex: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@string', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  psubscribe: {
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  pttl: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  publish: {
    flags: ['pubsub', 'loading', 'stale', 'fast'],
    categories: ['@pubsub', '@fast'],
  },
  pubsub: { flags: [], categories: ['@slow'] },
  'pubsub|channels': {
    flags: ['pubsub', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  'pubsub|help': { flags: ['loading', 'stale'], categories: ['@slow'] },
  'pubsub|numpat': {
    flags: ['pubsub', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  'pubsub|numsub': {
    flags: ['pubsub', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  'pubsub|shardchannels': {
    flags: ['pubsub', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  'pubsub|shardnumsub': {
    flags: ['pubsub', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  punsubscribe: {
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  quit: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'no_auth', 'allow_busy'],
    categories: ['@fast', '@connection'],
  },
  randomkey: {
    flags: ['readonly'],
    categories: ['@keyspace', '@read', '@slow'],
    tips: [
      'request_policy:all_shards',
      'response_policy:special',
      'nondeterministic_output',
    ],
  },
  readonly: {
    flags: ['loading', 'stale', 'fast'],
    categories: ['@fast', '@connection'],
  },
  readwrite: {
    flags: ['loading', 'stale', 'fast'],
    categories: ['@fast', '@connection'],
  },
  rename: {
    flags: ['write'],
    categories: ['@keyspace', '@write', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
      { flags: ['OW', 'update'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  renamenx: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
      { flags: ['OW', 'insert'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  reset: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'no_auth', 'allow_busy'],
    categories: ['@fast', '@connection'],
  },
  rpop: {
    flags: ['write', 'fast'],
    categories: ['@write', '@list', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  rpoplpush: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@list', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
      { flags: ['RW', 'insert'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  rpush: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@list', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  rpushx: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@list', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  sadd: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@set', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  scan: {
    flags: ['readonly'],
    categories: ['@keyspace', '@read', '@slow'],
    tips: [
      'nondeterministic_output',
      'request_policy:special',
      'response_policy:special',
    ],
  },
  scard: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@set', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  script: { flags: [], categories: ['@slow'] },
  'script|debug': { flags: ['noscript'], categories: ['@slow', '@scripting'] },
  'script|exists': {
    flags: ['noscript'],
    categories: ['@slow', '@scripting'],
    tips: ['request_policy:all_shards', 'response_policy:agg_logical_and'],
  },
  'script|flush': {
    flags: ['noscript'],
    categories: ['@slow', '@scripting'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  'script|help': {
    flags: ['loading', 'stale'],
    categories: ['@slow', '@scripting'],
  },
  'script|kill': {
    flags: ['noscript', 'allow_busy'],
    categories: ['@slow', '@scripting'],
    tips: ['request_policy:all_shards', 'response_policy:one_succeeded'],
  },
  'script|load': {
    flags: ['noscript', 'stale'],
    categories: ['@slow', '@scripting'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  sdiff: {
    flags: ['readonly'],
    categories: ['@read', '@set', '@slow'],
    tips: ['nondeterministic_output_order'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  sdiffstore: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@set', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: -1, keyStep: 1 },
    ],
  },
  select: {
    flags: ['loading', 'stale', 'fast'],
    categories: ['@fast', '@connection'],
  },
  set: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@string', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update', 'variable_flags'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        notes: 'RW and ACCESS due to the optional `GET` argument',
      },
    ],
  },
  setbit: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@bitmap', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  setex: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@string', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  setnx: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@string', '@fast'],
    keySpecs: [
      { flags: ['OW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  setrange: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@string', '@slow'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  shutdown: {
    flags: ['admin', 'noscript', 'loading', 'stale', 'no_multi', 'allow_busy'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  sinter: {
    flags: ['readonly'],
    categories: ['@read', '@set', '@slow'],
    tips: ['nondeterministic_output_order'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  sintercard: {
    flags: ['readonly', 'movablekeys'],
    categories: ['@read', '@set', '@slow'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  sinterstore: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@set', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: -1, keyStep: 1 },
    ],
  },
  sismember: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@set', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  slowlog: { flags: [], categories: ['@slow'] },
  'slowlog|get': {
    flags: ['admin', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
    tips: ['request_policy:all_nodes', 'nondeterministic_output'],
  },
  'slowlog|help': { flags: ['loading', 'stale'], categories: ['@slow'] },
  'slowlog|len': {
    flags: ['admin', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
    tips: [
      'request_policy:all_nodes',
      'response_policy:agg_sum',
      'nondeterministic_output',
    ],
  },
  'slowlog|reset': {
    flags: ['admin', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
    tips: ['request_policy:all_nodes', 'response_policy:all_succeeded'],
  },
  smembers: {
    flags: ['readonly'],
    categories: ['@read', '@set', '@slow'],
    tips: ['nondeterministic_output_order'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  smismember: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@set', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  smove: {
    flags: ['write', 'fast'],
    categories: ['@write', '@set', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
      { flags: ['RW', 'insert'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  sort: {
    flags: ['write', 'denyoom', 'movablekeys'],
    categories: [
      '@write',
      '@set',
      '@sortedset',
      '@list',
      '@slow',
      '@dangerous',
    ],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 0,
        notes:
          "For the optional BY/GET keyword. It is marked 'unknown' because the key names derive from the content of the key we sort",
        beginSearchUnknown: true,
        findKeysUnknown: true,
      },
      {
        flags: ['OW', 'update'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 0,
        notes:
          "For the optional STORE keyword. It is marked 'unknown' because the keyword can appear anywhere in the argument array",
        beginSearchUnknown: true,
        findKeysUnknown: true,
      },
    ],
  },
  sort_ro: {
    flags: ['readonly', 'movablekeys'],
    categories: ['@read', '@set', '@sortedset', '@list', '@slow', '@dangerous'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 0,
        notes:
          "For the optional BY/GET keyword. It is marked 'unknown' because the key names derive from the content of the key we sort",
        beginSearchUnknown: true,
        findKeysUnknown: true,
      },
    ],
  },
  spop: {
    flags: ['write', 'fast'],
    categories: ['@write', '@set', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  spublish: {
    flags: ['pubsub', 'loading', 'stale', 'fast'],
    categories: ['@pubsub', '@fast'],
    keySpecs: [
      { flags: ['not_key'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  srandmember: {
    flags: ['readonly'],
    categories: ['@read', '@set', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  srem: {
    flags: ['write', 'fast'],
    categories: ['@write', '@set', '@fast'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  sscan: {
    flags: ['readonly'],
    categories: ['@read', '@set', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  ssubscribe: {
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
    keySpecs: [
      { flags: ['not_key'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  strlen: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@string', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  subscribe: {
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  substr: {
    flags: ['readonly'],
    categories: ['@read', '@string', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  sunion: {
    flags: ['readonly'],
    categories: ['@read', '@set', '@slow'],
    tips: ['nondeterministic_output_order'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  sunionstore: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@set', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: -1, keyStep: 1 },
    ],
  },
  sunsubscribe: {
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
    keySpecs: [
      { flags: ['not_key'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  time: {
    flags: ['loading', 'stale', 'fast'],
    categories: ['@fast'],
    tips: ['nondeterministic_output'],
  },
  touch: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    tips: ['request_policy:multi_shard', 'response_policy:agg_sum'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 }],
  },
  ttl: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  type: {
    flags: ['readonly', 'fast'],
    categories: ['@keyspace', '@read', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  unlink: {
    flags: ['write', 'fast'],
    categories: ['@keyspace', '@write', '@fast'],
    tips: ['request_policy:multi_shard', 'response_policy:agg_sum'],
    keySpecs: [
      { flags: ['RM', 'delete'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 },
    ],
  },
  unsubscribe: {
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  unwatch: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'allow_busy'],
    categories: ['@fast', '@transaction'],
  },
  watch: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'allow_busy'],
    categories: ['@fast', '@transaction'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: -1, keyStep: 1 }],
  },
  xack: {
    flags: ['write', 'fast'],
    categories: ['@write', '@stream', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xadd: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@stream', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      {
        flags: ['RW', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        notes:
          'UPDATE instead of INSERT because of the optional trimming feature',
      },
    ],
  },
  xautoclaim: {
    flags: ['write', 'fast'],
    categories: ['@write', '@stream', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xclaim: {
    flags: ['write', 'fast'],
    categories: ['@write', '@stream', '@fast'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xdel: {
    flags: ['write', 'fast'],
    categories: ['@write', '@stream', '@fast'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xgroup: { flags: [], categories: ['@slow'] },
  'xgroup|create': {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  'xgroup|createconsumer': {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  'xgroup|delconsumer': {
    flags: ['write'],
    categories: ['@write', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  'xgroup|destroy': {
    flags: ['write'],
    categories: ['@write', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  'xgroup|help': {
    flags: ['loading', 'stale'],
    categories: ['@stream', '@slow'],
  },
  'xgroup|setid': {
    flags: ['write'],
    categories: ['@write', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  xinfo: { flags: [], categories: ['@slow'] },
  'xinfo|consumers': {
    flags: ['readonly'],
    categories: ['@read', '@stream', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  'xinfo|groups': {
    flags: ['readonly'],
    categories: ['@read', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  'xinfo|help': {
    flags: ['loading', 'stale'],
    categories: ['@stream', '@slow'],
  },
  'xinfo|stream': {
    flags: ['readonly'],
    categories: ['@read', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  xlen: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@stream', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  xpending: {
    flags: ['readonly'],
    categories: ['@read', '@stream', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xrange: {
    flags: ['readonly'],
    categories: ['@read', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xread: {
    flags: ['readonly', 'blocking', 'movablekeys'],
    categories: ['@read', '@stream', '@slow', '@blocking'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 0,
        lastKey: -1,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STREAMS', startFrom: 1 },
        limit: 2,
      },
    ],
  },
  xreadgroup: {
    flags: ['write', 'blocking', 'movablekeys'],
    categories: ['@write', '@stream', '@slow', '@blocking'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 0,
        lastKey: -1,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STREAMS', startFrom: 4 },
        limit: 2,
      },
    ],
  },
  xrevrange: {
    flags: ['readonly'],
    categories: ['@read', '@stream', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xsetid: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@stream', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  xtrim: {
    flags: ['write'],
    categories: ['@write', '@stream', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zadd: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zcard: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@sortedset', '@fast'],
    keySpecs: [{ flags: ['RO'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 }],
  },
  zcount: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zdiff: {
    flags: ['readonly', 'movablekeys'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  zdiffstore: {
    flags: ['write', 'denyoom', 'movablekeys'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  zincrby: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@sortedset', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  zinter: {
    flags: ['readonly', 'movablekeys'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  zintercard: {
    flags: ['readonly', 'movablekeys'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  zinterstore: {
    flags: ['write', 'denyoom', 'movablekeys'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  zlexcount: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zmpop: {
    flags: ['write', 'movablekeys'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  zmscore: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zpopmax: {
    flags: ['write', 'fast'],
    categories: ['@write', '@sortedset', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  zpopmin: {
    flags: ['write', 'fast'],
    categories: ['@write', '@sortedset', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'delete'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  zrandmember: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrange: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrangebylex: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrangebyscore: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrangestore: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: 0, keyStep: 1 },
    ],
  },
  zrank: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrem: {
    flags: ['write', 'fast'],
    categories: ['@write', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zremrangebylex: {
    flags: ['write'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zremrangebyrank: {
    flags: ['write'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zremrangebyscore: {
    flags: ['write'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RW', 'delete'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrevrange: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrevrangebylex: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrevrangebyscore: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zrevrank: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zscan: {
    flags: ['readonly'],
    categories: ['@read', '@sortedset', '@slow'],
    tips: ['nondeterministic_output'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zscore: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@sortedset', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  zunion: {
    flags: ['readonly', 'movablekeys'],
    categories: ['@read', '@sortedset', '@slow'],
    keySpecs: [
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
  zunionstore: {
    flags: ['write', 'denyoom', 'movablekeys'],
    categories: ['@write', '@sortedset', '@slow'],
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['RO', 'access'],
        beginSearchIndex: 2,
        lastKey: 0,
        keyStep: 1,
        findKeysKeynum: { keyNumIdx: 0, firstKey: 1, keyStep: 1 },
      },
    ],
  },
}

export const REDIS_74: CommandTableDelta = {
  hexpire: { flags: ['write', 'denyoom', 'fast'] },
  hexpireat: { flags: ['write', 'denyoom', 'fast'] },
  hgetdel: null,
  hgetex: null,
  hpexpire: { flags: ['write', 'denyoom', 'fast'] },
  hpexpireat: { flags: ['write', 'denyoom', 'fast'] },
  hpttl: { tips: [] },
  hsetex: null,
  httl: { tips: [] },
}

export const REDIS_72: CommandTableDelta = {
  hexpire: null,
  hexpireat: null,
  hpersist: null,
  hpexpire: null,
  hpexpireat: null,
  hpttl: null,
  httl: null,
  sinterstore: {
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: -1, keyStep: 1 },
    ],
  },
}

export const REDIS_70: CommandTableDelta = {
  blmove: { flags: ['write', 'denyoom', 'noscript', 'blocking'] },
  blpop: { flags: ['write', 'noscript', 'blocking'] },
  brpop: { flags: ['write', 'noscript', 'blocking'] },
  bzpopmax: { flags: ['write', 'noscript', 'blocking', 'fast'] },
  bzpopmin: { flags: ['write', 'noscript', 'blocking', 'fast'] },
  'client|setinfo': null,
  'client|setname': { tips: [] },
  'cluster|shards': { flags: ['stale'] },
  'cluster|slots': { flags: ['stale'] },
  'config|resetstat': { tips: [] },
  'config|rewrite': { tips: [] },
  msetnx: { tips: ['request_policy:multi_shard', 'response_policy:agg_min'] },
  randomkey: { tips: ['request_policy:all_shards', 'nondeterministic_output'] },
  scan: { tips: ['nondeterministic_output', 'request_policy:special'] },
}

export const REDIS_62: CommandTableDelta = {
  acl: {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  'acl|dryrun': null,
  'acl|help': null,
  'acl|whoami': null,
  auth: { flags: ['noscript', 'loading', 'stale', 'fast', 'no_auth'] },
  blmove: { flags: ['write', 'denyoom', 'noscript'] },
  blmpop: null,
  blpop: { flags: ['write', 'noscript'] },
  brpop: { flags: ['write', 'noscript'] },
  bzmpop: null,
  bzpopmax: { flags: ['write', 'noscript', 'fast'] },
  bzpopmin: { flags: ['write', 'noscript', 'fast'] },
  client: {
    flags: ['admin', 'noscript', 'random', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous', '@connection'],
  },
  'client|getname': null,
  'client|help': null,
  'client|id': null,
  'client|info': null,
  'client|kill': null,
  'client|list': null,
  'client|no-evict': null,
  'client|setname': null,
  cluster: {
    flags: ['admin', 'random', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  'cluster|info': null,
  'cluster|myid': null,
  'cluster|nodes': null,
  'cluster|shards': null,
  'cluster|slots': null,
  command: { flags: ['random', 'loading', 'stale'] },
  'command|count': null,
  'command|docs': null,
  'command|getkeys': null,
  'command|getkeysandflags': null,
  'command|help': null,
  'command|info': null,
  'command|list': null,
  config: {
    flags: ['admin', 'noscript', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  'config|get': null,
  'config|help': null,
  'config|resetstat': null,
  'config|rewrite': null,
  'config|set': null,
  discard: { flags: ['noscript', 'loading', 'stale', 'fast'] },
  echo: { flags: ['fast'] },
  eval: { flags: ['noscript', 'skip_monitor', 'may_replicate', 'movablekeys'] },
  eval_ro: null,
  evalsha: {
    flags: ['noscript', 'skip_monitor', 'may_replicate', 'movablekeys'],
  },
  evalsha_ro: null,
  expiretime: null,
  fcall: null,
  fcall_ro: null,
  function: null,
  'function|delete': null,
  'function|dump': null,
  'function|flush': null,
  'function|help': null,
  'function|kill': null,
  'function|list': null,
  'function|load': null,
  'function|restore': null,
  'function|stats': null,
  hello: { flags: ['noscript', 'loading', 'stale', 'fast', 'no_auth'] },
  hgetall: { flags: ['readonly', 'random'] },
  hkeys: { flags: ['readonly', 'sort_for_script'] },
  hrandfield: { flags: ['readonly', 'random'] },
  hscan: { flags: ['readonly', 'random'] },
  hvals: { flags: ['readonly', 'sort_for_script'] },
  info: { flags: ['random', 'loading', 'stale'] },
  keys: { flags: ['readonly', 'sort_for_script'] },
  lastsave: { flags: ['random', 'loading', 'stale', 'fast'] },
  lmpop: null,
  multi: { flags: ['noscript', 'loading', 'stale', 'fast'] },
  pexpiretime: null,
  pfcount: { flags: ['readonly', 'may_replicate'] },
  ping: { flags: ['stale', 'fast'] },
  psubscribe: { flags: ['denyoom', 'pubsub', 'noscript', 'loading', 'stale'] },
  pttl: { flags: ['readonly', 'random', 'fast'] },
  publish: { flags: ['pubsub', 'loading', 'stale', 'fast', 'may_replicate'] },
  pubsub: {
    flags: ['pubsub', 'random', 'loading', 'stale'],
    categories: ['@pubsub', '@slow'],
  },
  'pubsub|channels': null,
  'pubsub|help': null,
  'pubsub|numpat': null,
  'pubsub|numsub': null,
  'pubsub|shardchannels': null,
  'pubsub|shardnumsub': null,
  quit: null,
  randomkey: { flags: ['readonly', 'random'] },
  readonly: { flags: ['fast'], categories: ['@keyspace', '@fast'] },
  readwrite: { flags: ['fast'], categories: ['@keyspace', '@fast'] },
  reset: { flags: ['noscript', 'loading', 'stale', 'fast'] },
  scan: { flags: ['readonly', 'random'] },
  script: {
    flags: ['noscript', 'may_replicate'],
    categories: ['@slow', '@scripting'],
  },
  'script|debug': null,
  'script|exists': null,
  'script|flush': null,
  'script|help': null,
  'script|kill': null,
  'script|load': null,
  sdiff: { flags: ['readonly', 'sort_for_script'] },
  select: { categories: ['@keyspace', '@fast'] },
  shutdown: { flags: ['admin', 'noscript', 'loading', 'stale'] },
  sinter: { flags: ['readonly', 'sort_for_script'] },
  sintercard: null,
  slowlog: {
    flags: ['admin', 'random', 'loading', 'stale'],
    categories: ['@admin', '@slow', '@dangerous'],
  },
  'slowlog|get': null,
  'slowlog|help': null,
  'slowlog|len': null,
  'slowlog|reset': null,
  smembers: { flags: ['readonly', 'sort_for_script'] },
  sort_ro: null,
  spop: { flags: ['write', 'random', 'fast'] },
  spublish: null,
  srandmember: { flags: ['readonly', 'random'] },
  sscan: { flags: ['readonly', 'random'] },
  ssubscribe: null,
  subscribe: { flags: ['denyoom', 'pubsub', 'noscript', 'loading', 'stale'] },
  sunion: { flags: ['readonly', 'sort_for_script'] },
  sunsubscribe: null,
  time: { flags: ['random', 'loading', 'stale', 'fast'] },
  ttl: { flags: ['readonly', 'random', 'fast'] },
  unwatch: { flags: ['noscript', 'loading', 'stale', 'fast'] },
  watch: { flags: ['noscript', 'loading', 'stale', 'fast'] },
  xack: { flags: ['write', 'random', 'fast'] },
  xadd: { flags: ['write', 'denyoom', 'random', 'fast'] },
  xautoclaim: { flags: ['write', 'random', 'fast'] },
  xclaim: { flags: ['write', 'random', 'fast'] },
  xgroup: {
    flags: ['write', 'denyoom'],
    categories: ['@write', '@stream', '@slow'],
  },
  'xgroup|create': null,
  'xgroup|createconsumer': null,
  'xgroup|delconsumer': null,
  'xgroup|destroy': null,
  'xgroup|help': null,
  'xgroup|setid': null,
  xinfo: {
    flags: ['readonly', 'random'],
    categories: ['@read', '@stream', '@slow'],
  },
  'xinfo|consumers': null,
  'xinfo|groups': null,
  'xinfo|help': null,
  'xinfo|stream': null,
  xpending: { flags: ['readonly', 'random'] },
  xread: { flags: ['readonly', 'movablekeys'] },
  xreadgroup: { flags: ['write', 'movablekeys'] },
  xtrim: { flags: ['write', 'random'] },
  zintercard: null,
  zmpop: null,
  zrandmember: { flags: ['readonly', 'random'] },
  zscan: { flags: ['readonly', 'random'] },
}

export const VALKEY_80: CommandTableDelta = {
  'cluster|info': { flags: ['loading', 'stale'] },
  'cluster|myid': { flags: ['loading', 'stale'] },
  'cluster|nodes': { flags: ['loading', 'stale'] },
  georadius: {
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['OW', 'update', 'variable_flags'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STORE', startFrom: 6 },
      },
      {
        flags: ['OW', 'update', 'variable_flags'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STOREDIST', startFrom: 6 },
      },
    ],
  },
  georadiusbymember: {
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      {
        flags: ['OW', 'update', 'variable_flags'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STORE', startFrom: 5 },
      },
      {
        flags: ['OW', 'update', 'variable_flags'],
        beginSearchIndex: 0,
        lastKey: 0,
        keyStep: 1,
        beginSearchKeyword: { keyword: 'STOREDIST', startFrom: 5 },
      },
    ],
  },
  multi: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'no_multi', 'allow_busy'],
  },
  sinterstore: {
    keySpecs: [
      { flags: ['OW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
      { flags: ['RO', 'access'], beginSearchIndex: 2, lastKey: -1, keyStep: 1 },
    ],
  },
  watch: {
    flags: ['noscript', 'loading', 'stale', 'fast', 'no_multi', 'allow_busy'],
  },
}

export const VALKEY_90: CommandTableDelta = {
  exec: { flags: ['noscript', 'loading', 'stale', 'skip_commandlog'] },
  hexpire: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hexpireat: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hgetex: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      {
        flags: ['RW', 'access', 'update'],
        beginSearchIndex: 1,
        lastKey: 0,
        keyStep: 1,
      },
    ],
  },
  hpersist: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hpexpire: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hpexpireat: {
    flags: ['write', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'update'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hpttl: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  hsetex: {
    flags: ['write', 'denyoom', 'fast'],
    categories: ['@write', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RW', 'insert'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  httl: {
    flags: ['readonly', 'fast'],
    categories: ['@read', '@hash', '@fast'],
    keySpecs: [
      { flags: ['RO', 'access'], beginSearchIndex: 1, lastKey: 0, keyStep: 1 },
    ],
  },
  'script|exists': { flags: ['noscript', 'stale'] },
  'script|flush': { flags: ['noscript', 'stale'] },
}
